name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Bootstrap
        run: npm i lerna@3.18.4 && npx lerna bootstrap

      - name: Test
        run: npx lerna run test

      - name: Build Integration
        run: npx lerna run build --scope @lit-kit-demos/*
