name: CI

on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Bootstrap
        run: npm ci

      - name: Lib Tests
        run: npx lerna run test --scope @lit-kit/*

      - name: Integration Tests
        run: npx lerna run test --scope @lit-kit-examples/*

      - name: Build Integrations
        run: npx lerna run build --scope @lit-kit-examples/*
