name: CI

on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Bootstrap
        run: npm ci

      - name: Test
        run: npx lerna run test

      - name: Build Integration
        run: npx lerna run build --scope @lit-kit-examples/*
