name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Bootstrap
        run: npm i -g lerna && lerna bootstrap

      - name: Test
        run: lerna run test

      - name: Build Integrations
        run: lerna run build --scope=@lit-kit-demos/*
