name: Node.js Package
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npx lerna publish --canary --preid next --no-git-reset --yes
