name: PUBLISH

on:
  push:
    branches:
      - 'master'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - run: npm ci

      - run: npx lerna publish --canary --preid next --no-git-reset --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
